<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai Dosen Utama_score_dosen</name>
   <tag></tag>
   <elementGuidId>f53d7963-8ee4-4b12-935d-1068b1ad6333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_dosen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_dosen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>330b9b87-8acb-4915-92a6-3b8eedba0345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>5af59fe3-92e1-4081-af53-05c15c6838a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input</value>
      <webElementGuid>c4043966-952d-42b5-a900-16b5b35427b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_dosen</value>
      <webElementGuid>d5095f94-6e31-47ac-b63d-1add5badf2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a889efc-00a0-421f-bcde-d8e60a9e1a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog_1&quot;)/div[@class=&quot;modal d-block o_technical_modal&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content o_form_view ui-draggable&quot;]/main[@class=&quot;modal-body p-0&quot;]/div[@class=&quot;o_form_nosheet form-detail o_form_editable d-block o_form_saved&quot;]/div[@class=&quot;o_group row align-items-start&quot;]/div[@class=&quot;o_inner_group grid col-lg-6&quot;]/div[@class=&quot;o_wrap_field d-flex d-sm-contents flex-column mb-3 mb-sm-0&quot;]/div[@class=&quot;o_cell flex-grow-1 flex-sm-grow-0&quot;]/div[@class=&quot;o_row&quot;]/div[@class=&quot;o_field_widget o_field_float&quot;]/input[@id=&quot;score_dosen&quot;]</value>
      <webElementGuid>5891796f-6ce9-4926-8205-0aab4db468eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_dosen']</value>
      <webElementGuid>b70f7f69-abf6-44a9-b4ee-23a65bc4bc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog_1']/div/div/div/main/div/div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>4dc7bed0-248b-46b7-a3a9-1c3776028ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>53410f73-5687-42cd-aa2c-1e4e62d966f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'score_dosen' and @type = 'text']</value>
      <webElementGuid>19b93f8f-d817-4b89-b074-f6adc199e68d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
