<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mata Kuliah_matkul_id</name>
   <tag></tag>
   <elementGuidId>256ab1aa-fdb7-4531-8dee-cb480c1a8dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#matkul_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='matkul_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e33f997-86e0-415e-9c53-ce2bbba5597b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae69248f-9cd7-49bd-b674-c51329ed50d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>7dbfcd13-4ec7-4122-97d0-ad775e05815b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a5c0069-e5cd-4699-bc0d-e97276d8420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>matkul_id</value>
      <webElementGuid>b8d5cb1c-9756-4cd4-855c-9332696efdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matkul_id&quot;)</value>
      <webElementGuid>c34d2db6-4158-439a-af9b-c525d7fbfbbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='matkul_id']</value>
      <webElementGuid>b8c2793a-fd75-4b68-9983-e11fa0208693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>ad208b82-5110-4d63-897e-653ef3a1470a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'matkul_id']</value>
      <webElementGuid>e69a1860-fac7-4ed0-9abb-c3f99930a366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
