<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dosen Cadangan_dosen_cadangan_id</name>
   <tag></tag>
   <elementGuidId>ff509347-fdf9-4490-85fa-bd574c3281c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosen_cadangan_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosen_cadangan_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b56a804-2a33-4a3f-8df1-f94e2e344dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53c23c09-ced7-4d1c-9213-2da1f4bcdc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>7cd1ab70-c287-42d9-9edb-2df3e9ff3326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>825cbff2-1654-43b0-a31d-0814c7a77def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosen_cadangan_id</value>
      <webElementGuid>27d1d40a-cd4b-4993-851a-db5661f959e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosen_cadangan_id&quot;)</value>
      <webElementGuid>a17db1ea-dd5b-470b-8d24-78807ebab5a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosen_cadangan_id']</value>
      <webElementGuid>550b7a98-c431-4605-914e-8450a8d1f572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>f3b7a96d-4f4d-4d78-ad82-47419a8a87e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dosen_cadangan_id']</value>
      <webElementGuid>0501449c-bef0-400e-9d9d-1c1df3f847f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
