<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jurusan_jurusan_id</name>
   <tag></tag>
   <elementGuidId>c6d2c009-49ee-4493-96ae-3e380185d5b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jurusan_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jurusan_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8acda39b-e0b9-45f1-af99-392195f25950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8aebaa2b-acfe-4fba-bedd-dd540292c70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>f97dda3b-b28a-456a-bdd0-079bb9902f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a8fe8790-bf8c-40d1-bb44-9422f42adb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jurusan_id</value>
      <webElementGuid>225635a0-75ec-48da-bfda-c8a555869848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jurusan_id&quot;)</value>
      <webElementGuid>3d3d888f-98e6-4db9-b119-d6e2961b8b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jurusan_id']</value>
      <webElementGuid>f052ae39-d507-4ca4-bdfe-fa1c707d6435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>59bffe6c-ddc9-49b2-82e7-9a92aa517d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jurusan_id']</value>
      <webElementGuid>3d864192-53b3-4e41-91b0-b756314952a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
