<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dosen Utama_dosen_utama_id</name>
   <tag></tag>
   <elementGuidId>31ff6511-f5ae-4b40-a118-f252de6c25c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosen_utama_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosen_utama_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de06d5dd-58d5-456a-a500-411ea38ea335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a011aa0-9497-43b3-b396-cf046bc79002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>1a554060-c7b0-4d0a-941f-b9fd979e7abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7c8a3a35-645b-494a-b503-e6b55532b51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosen_utama_id</value>
      <webElementGuid>415c0cee-6cb3-4ce1-a90f-09c481127c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosen_utama_id&quot;)</value>
      <webElementGuid>b412f08b-c8b7-49b0-a80d-860f5ed2463b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosen_utama_id']</value>
      <webElementGuid>273dbc7d-e069-498a-960b-80d9d25f61fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/input</value>
      <webElementGuid>513fba7e-8f20-4ccf-b9af-a5e3dce23a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dosen_utama_id']</value>
      <webElementGuid>f7dc245e-fa44-49ba-971b-768c1679f9d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
