<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai Dosen Utama_score_dosen</name>
   <tag></tag>
   <elementGuidId>17604bd3-3f25-40c6-a2e3-eecf9354d9b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_dosen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_dosen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f612aa-8988-418f-92a1-793136fcf0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>7c5f13d6-a416-4263-b277-bf144a1d792b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input</value>
      <webElementGuid>dfde9b2c-6b81-4c23-b98d-540143bf2863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_dosen</value>
      <webElementGuid>05742a7d-e59a-45a9-8745-96c0d28e9cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>929e663c-96e0-4707-b121-c5e2d83514f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog_1&quot;)/div[@class=&quot;modal d-block o_technical_modal&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content o_form_view ui-draggable&quot;]/main[@class=&quot;modal-body p-0&quot;]/div[@class=&quot;o_form_nosheet form-detail o_form_editable d-block o_form_saved&quot;]/div[@class=&quot;o_group row align-items-start&quot;]/div[@class=&quot;o_inner_group grid col-lg-6&quot;]/div[@class=&quot;o_wrap_field d-flex d-sm-contents flex-column mb-3 mb-sm-0&quot;]/div[@class=&quot;o_cell flex-grow-1 flex-sm-grow-0&quot;]/div[@class=&quot;o_row&quot;]/div[@class=&quot;o_field_widget o_field_float&quot;]/input[@id=&quot;score_dosen&quot;]</value>
      <webElementGuid>c0d30ed8-28a6-48ce-9d53-0db061779ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_dosen']</value>
      <webElementGuid>c34217c7-e71b-4dbf-aa49-05b86005df22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog_1']/div/div/div/main/div/div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>2286452e-d08f-40c5-a2c2-349c1213c6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>ba19275b-c48a-4d00-a999-34f8734cb6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'score_dosen' and @type = 'text']</value>
      <webElementGuid>bbc346f3-4029-4770-aa0a-42d1992ea730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
