<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2,00</name>
   <tag></tag>
   <elementGuidId>f18e078c-bd3b-4040-a4bf-d7aa0c38e69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;score_dosen&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@name='score_dosen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ec18410e-b1fa-4c19-baeb-f161b1fa48f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_data_cell cursor-pointer o_field_cell o_list_number</value>
      <webElementGuid>d5759853-edec-4434-83f2-9b7c6fed6ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-delay</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>60042442-dedb-47cf-adf2-5086a58eeb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5ae81584-5fa0-4bfb-b743-58f707dae281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score_dosen</value>
      <webElementGuid>8923312f-a673-4930-8f82-4921fd26e260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2,00</value>
      <webElementGuid>f3aeae1b-edca-478f-b406-038b994e584c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client mk_sidebar_type_large&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_action o_view_controller o_form_view&quot;]/div[@class=&quot;o_form_view_container&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_form_editable d-flex flex-column o_form_dirty&quot;]/div[@class=&quot;o_form_sheet_bg&quot;]/div[@class=&quot;o_form_sheet position-relative clearfix&quot;]/div[@class=&quot;o_notebook d-flex w-100 horizontal flex-column&quot;]/div[@class=&quot;o_notebook_content tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/div[@class=&quot;o_field_widget o_field_one2many&quot;]/div[@class=&quot;o_field_x2many o_field_x2many_list&quot;]/div[@class=&quot;o_list_renderer o_renderer table-responsive&quot;]/table[@class=&quot;o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped&quot;]/tbody[@class=&quot;ui-sortable&quot;]/tr[@class=&quot;o_data_row&quot;]/td[@class=&quot;o_data_cell cursor-pointer o_field_cell o_list_number&quot;]</value>
      <webElementGuid>674848fc-235b-457a-a8ed-1e6f32b19727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@name='score_dosen']</value>
      <webElementGuid>6ee39ce1-6145-4db4-8436-a93b89dfa8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bahasa'])[1]/following::td[1]</value>
      <webElementGuid>83034297-2cb7-4e56-9291-a3fd4a4d15e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teks'])[1]/following::td[2]</value>
      <webElementGuid>92895ec6-fc28-4444-b276-49d2c7218d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teks'])[2]/preceding::td[7]</value>
      <webElementGuid>b07c35c6-4694-4830-9479-b0d31abdf39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ddd'])[1]/preceding::td[8]</value>
      <webElementGuid>b5054446-dc13-4f5c-9057-200ace1b6251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2,00']/parent::*</value>
      <webElementGuid>16c93bf8-7832-44cc-82cb-e98c9b083f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>f736ecee-c6b8-447c-8e1c-707b60bc8010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@name = 'score_dosen' and (text() = '2,00' or . = '2,00')]</value>
      <webElementGuid>d5cddfcc-66a1-4ed2-a973-9cf0ae4666cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
