<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mata Kuliah_matkul_id</name>
   <tag></tag>
   <elementGuidId>345b256c-c3e3-47e2-871b-e4825f1b73e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#matkul_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='matkul_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8900a2e-366c-431a-9907-603d613e8e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32c415e1-451b-4c1e-953c-11ac4ad5665f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>ba057f43-3f40-450c-ab74-31c4623d59d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>343bea6a-774e-437c-8e25-1c0b449160a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>matkul_id</value>
      <webElementGuid>a82146b5-e21d-4a1c-a4ea-e6f8239ed160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matkul_id&quot;)</value>
      <webElementGuid>2f097aa5-a12a-418e-8432-3a93ff154f46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='matkul_id']</value>
      <webElementGuid>8dcdef14-2e2f-4823-99aa-e12ef199f981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a4a8d4a8-9777-4f3d-b058-edd50be32c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'matkul_id']</value>
      <webElementGuid>7ba6c7a8-b1a7-44ca-a19d-62f2af15c3f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
