<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jurusan_jurusan_id</name>
   <tag></tag>
   <elementGuidId>179907d2-cf1d-4777-9e30-2dce38b31b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jurusan_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jurusan_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ce1950a-8aa5-4f6e-b57f-a85d670a1d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e286684f-0677-494b-ab18-4b109b39de11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>c1b2b9b5-71c3-4fac-9f5d-f66c239a558d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3819bd1a-98e5-4883-aa8d-5852169368f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jurusan_id</value>
      <webElementGuid>4586d0cd-a660-4290-905d-1a24bcb0a8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jurusan_id&quot;)</value>
      <webElementGuid>2bb006db-f14f-4eae-b532-063fc44e3d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jurusan_id']</value>
      <webElementGuid>53c6599f-e322-4afe-bd28-bf256c37c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>8a31a1e3-a740-4804-b115-3d3c5bb14467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jurusan_id']</value>
      <webElementGuid>acb98690-1f0d-4214-84e6-dab9db5815ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
