<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prodi_prodi_id</name>
   <tag></tag>
   <elementGuidId>353b00d1-af01-41eb-82bb-5e446b8cb7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prodi_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prodi_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b4b82f8-cf36-4498-8f3e-8ef740dced6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ba58b81-1439-4849-887a-b4b9a9f83480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>643712dd-8aba-474a-b0da-6883829209b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fbbc2fee-7d09-4095-9e96-dfbc81c6407a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prodi_id</value>
      <webElementGuid>ce808d82-77e8-4ba3-b3eb-794685f05695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prodi_id&quot;)</value>
      <webElementGuid>fb0a2a99-6c2c-47f2-917f-958feba1b23c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prodi_id']</value>
      <webElementGuid>0c0baf8a-f1d8-4c08-b567-5ae431617a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>0f049592-2128-4306-978e-13e5fef1e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'prodi_id']</value>
      <webElementGuid>34cd83c1-dd13-468b-ae88-d9d7c4cbee20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
