<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Datetime_sh_survey_start_date_time</name>
   <tag></tag>
   <elementGuidId>65b13894-8065-4ea6-af43-82827b38b8e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sh_survey_start_date_time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sh_survey_start_date_time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5741bad-7704-452e-837c-5e17e9f9b38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3046e9cc-cd7b-4af8-b810-7da494fcc46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_datepicker_input o_input datetimepicker-input</value>
      <webElementGuid>896d6d2d-761d-40ab-b2a2-8586b6a30963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>85357c20-1cf3-47c3-9759-4e0c6b6a62d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sh_survey_start_date_time</value>
      <webElementGuid>c4061793-7bef-4b94-8be9-63c49d506fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sh_survey_start_date_time&quot;)</value>
      <webElementGuid>da19e872-3ce2-4394-8e7c-d9bca788da90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sh_survey_start_date_time']</value>
      <webElementGuid>98b0c5cb-99eb-4bb2-aefd-c57a5ff733a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>46047a64-86b5-47a7-aff0-f0a1fcd37b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sh_survey_start_date_time']</value>
      <webElementGuid>9924d241-cd17-45cc-8c8f-44e948188f82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
