<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Datetime_sh_survey_end_date_time</name>
   <tag></tag>
   <elementGuidId>ba06000e-9ba4-4ffe-a836-de2a48dd7298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sh_survey_end_date_time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sh_survey_end_date_time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>526259e4-fc50-4498-b778-a9db8439af08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b66fe3f3-7475-4a48-8aca-5571964c9514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_datepicker_input o_input datetimepicker-input</value>
      <webElementGuid>a05986ff-a5c9-4391-a26f-3c4e4a041ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>64c1183f-9303-4c1e-b22a-996143345f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sh_survey_end_date_time</value>
      <webElementGuid>580522b3-808b-4c88-aff1-975cc2c2abd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sh_survey_end_date_time&quot;)</value>
      <webElementGuid>3a30e932-3b3b-4bc1-9e20-472d71a83e09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sh_survey_end_date_time']</value>
      <webElementGuid>e0645006-6fde-4899-adda-a8e169e1be32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>e8b1dcef-8cf3-46f5-8c4e-e01dbe91629e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sh_survey_end_date_time']</value>
      <webElementGuid>98c6a1f7-621d-4120-aed4-95ac8daeec8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
