<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__fa fa-chevron-right btn btn-seconda_866a5d</name>
   <tag></tag>
   <elementGuidId>00b9750e-027a-4eec-a530-cf6a35105f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o_x2m_control_panel > div.o_cp_pager > nav.o_pager.align-items-center.d-flex.gap-2 > span.btn-group > button.fa.fa-chevron-right.btn.btn-secondary.o_pager_next.px-2.rounded-end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea6361ea-b449-4cf3-b7b4-3124e7d62fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc6032aa-c30e-4009-9ef7-b50809db9ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-right btn btn-secondary o_pager_next px-2 rounded-end</value>
      <webElementGuid>2533fcb4-4aeb-470c-8620-6544057a024a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>1ab5e6c1-fb91-4496-9143-1fbd625de75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>abf4c0ac-c8f2-457c-b6d7-2b43b7ef62dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6350e326-c1b2-4356-b2ea-5f5393c49eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client mk_sidebar_type_large&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_action o_view_controller o_form_view&quot;]/div[@class=&quot;o_form_view_container&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_survey_form o_form_editable d-flex flex-column o_form_saved&quot;]/div[@class=&quot;o_form_sheet_bg&quot;]/div[@class=&quot;o_form_sheet position-relative clearfix&quot;]/div[@class=&quot;o_notebook d-flex w-100 horizontal flex-column&quot;]/div[@class=&quot;o_notebook_content tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/div[@class=&quot;o_field_widget o_field_question_page_one2many o_field_one2many&quot;]/div[@class=&quot;o_field_x2many o_field_x2many_list&quot;]/div[@class=&quot;o_x2m_control_panel&quot;]/div[@class=&quot;o_cp_pager&quot;]/nav[@class=&quot;o_pager align-items-center d-flex gap-2&quot;]/span[@class=&quot;btn-group&quot;]/button[@class=&quot;fa fa-chevron-right btn btn-secondary o_pager_next px-2 rounded-end&quot;]</value>
      <webElementGuid>49697b62-79ea-4c47-bedd-6c2e5b9ff248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[14]</value>
      <webElementGuid>b1f43c05-7904-49bd-b146-cc565a5a5f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/nav/span[2]/button[2]</value>
      <webElementGuid>10563556-ac4b-4a1f-8d4f-671aa4836ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>768d9b43-7eb9-4acc-bd0e-92431c7ab79b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
