<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai Ketua Jurusan_score_kajur</name>
   <tag></tag>
   <elementGuidId>af14c2ed-05c9-4af9-a5d5-a11023f3ae92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_kajur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_kajur']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2e68bac-6f62-4209-8373-e63344fc3064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>9e20d51f-889d-4a75-88d9-9275e8b98028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input</value>
      <webElementGuid>5bfdb2a8-53c6-4c75-9a86-e6f9c4c39b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_kajur</value>
      <webElementGuid>c0c2c1e0-e8a0-419a-be45-0e1316bf69a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec3f7409-0732-42e1-816e-053fe91051fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_kajur&quot;)</value>
      <webElementGuid>1a52530e-d38d-47f6-9ebb-3264c0493c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_kajur']</value>
      <webElementGuid>f0920e90-3a22-4e2f-976b-2c7215275dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog_1']/div/div/div/main/div/div[3]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>14a7957c-a9b1-434c-9c70-cbb37b8ff2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>70ccd2fd-1e04-490d-8836-725eb8b23771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'score_kajur' and @type = 'text']</value>
      <webElementGuid>d46fe134-ba7e-4cb2-bd2a-3bcb88b07a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
