<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Pengaturan_o_iframe</name>
   <tag></tag>
   <elementGuidId>9a122f34-a4be-4c10-9b34-61debd521113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.o_iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e0e5f0a4-af44-42f7-992b-2adc348668c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_iframe</value>
      <webElementGuid>7854fa56-10c2-46d0-8894-e57328e40b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-ready</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c8d94e3a-aa2a-4e46-8833-efcd11fadcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/website/force/1?path=%2F</value>
      <webElementGuid>25e47f66-b6ab-4c46-ab4b-0b49a4b7610d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-wysiwyg</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff73c606-abae-41c3-8ad6-e6ce9b665116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client mk_sidebar_type_large&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_website_preview&quot;]/div[@class=&quot;o_iframe_container&quot;]/iframe[@class=&quot;o_iframe&quot;]</value>
      <webElementGuid>bda981e5-475c-40a3-a1fd-c70d8555dde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>b5f3da4b-d111-465c-bcb5-8d9efe75125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/website/force/1?path=%2F']</value>
      <webElementGuid>d72874f7-be25-4b33-8ae6-3cba8a03a5fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
