<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Soal Uji Coba Sistem(9)_checkbox-comp-8</name>
   <tag></tag>
   <elementGuidId>a6e46db0-dc8d-46e3-a16c-b2a770e868f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-comp-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-comp-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ebd7ee6-e78f-4582-bde0-fd27e1a55f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5df72ede-5aee-43d8-a6f0-b4f3b3ef7bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>15f2a63f-9b6b-444e-9a12-366a8543668e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-comp-8</value>
      <webElementGuid>fc77f73c-36cf-4227-82f2-faef956da829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-comp-8&quot;)</value>
      <webElementGuid>cbd5c72b-3896-4814-b204-b66d8291798d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-comp-8']</value>
      <webElementGuid>6ef44650-3d01-4004-a0d0-3171ed185190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>1f336b0a-2a9a-4055-a995-3c0408b18dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox-comp-8']</value>
      <webElementGuid>8f7e43a7-9c99-4ad8-9a55-5ef5f1182b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
