<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai Dosen Utama_score_dosen</name>
   <tag></tag>
   <elementGuidId>979f72c0-2b40-4ccf-8686-5586143e992e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_dosen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_dosen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a42f360-a5bb-4b9e-9132-50c46e5ece13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>f6720206-07ed-4a89-886f-ed7cea614a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_input</value>
      <webElementGuid>8a0d2685-f32b-4c22-b37c-57fbf4579f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_dosen</value>
      <webElementGuid>a3ac74ed-7e74-49fb-b5c4-438cca1bb045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>300298a1-b43a-4e4b-a98a-492c1e4792e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_dosen&quot;)</value>
      <webElementGuid>c944dbe2-6dbe-4893-9457-e5eb1b11cf67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_dosen']</value>
      <webElementGuid>d89efa73-0911-4adb-a117-83a7ea38174f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog_1']/div/div/div/main/div/div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>e6faad3d-53f1-4fbc-8f37-cec005af9eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>dc7ac2cf-36b6-43a3-bddc-097633d562bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'score_dosen' and @type = 'text']</value>
      <webElementGuid>ac41b37a-fc31-41b6-b5e4-68e292992372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
