<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Penentu Ujian</name>
   <tag></tag>
   <elementGuidId>c500a4f4-a5b7-4ca4-b3e0-e4331a402723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Penentu Ujian')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>131378de-6798-41f9-bee7-e9c760e5567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item focus</value>
      <webElementGuid>574ecf34-f674-4718-9d48-ba0061d26c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d5df2197-9864-4d03-bff4-7a5819ded586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5fac1a1f-7db1-4923-8c3a-b470ce3689d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#menu_id=212&amp;action=265</value>
      <webElementGuid>76d841ec-4ee6-4e8a-823a-279b67bc34c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-xmlid</name>
      <type>Main</type>
      <value>cdn_penilaian_cbt.penentu_nilai_menu</value>
      <webElementGuid>570060a1-9a4a-4a47-b549-cca52b292f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section</name>
      <type>Main</type>
      <value>212</value>
      <webElementGuid>773e348e-6939-4903-a5c3-d7e6a384b3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penentu Ujian</value>
      <webElementGuid>cef3e861-4a1f-4a0b-a14d-3aa0584f2ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client mk_sidebar_type_large&quot;]/header[@class=&quot;o_navbar&quot;]/nav[@class=&quot;o_main_navbar&quot;]/div[@class=&quot;o_menu_sections d-none d-md-flex flex-grow-1 flex-shrink-1&quot;]/div[@class=&quot;o-dropdown dropdown o-dropdown--no-caret show&quot;]/div[@class=&quot;o-dropdown--menu dropdown-menu d-block&quot;]/a[@class=&quot;dropdown-item focus&quot;]</value>
      <webElementGuid>314c7113-f7eb-449b-9746-37913703a3c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Penentu Ujian')]</value>
      <webElementGuid>8e8a467b-567a-445d-a03f-4fdba36d2d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketua Jurusan'])[1]/following::a[1]</value>
      <webElementGuid>e9fc3fee-0b94-4dc4-932a-aa77f2788160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen'])[1]/following::a[1]</value>
      <webElementGuid>de532528-bebe-49b7-a050-4b739396bec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirbindikjar'])[1]/preceding::a[1]</value>
      <webElementGuid>de6b2ae4-3b1d-495b-a82d-b2380f92e17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harnyoto, S.T., M.M. (Kajur)'])[1]/preceding::a[3]</value>
      <webElementGuid>d5961bd7-b7ed-465c-a7a0-12b9fd6a0ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penentu Ujian']/parent::*</value>
      <webElementGuid>fb12d378-dfe4-4f08-97b8-2ff24c67f681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#menu_id=212&amp;action=265')]</value>
      <webElementGuid>191d2926-d5d6-45ce-8526-6f3eb7676739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>e5e20c6f-e49f-40fb-95e4-eccc6de7d77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#menu_id=212&amp;action=265' and (text() = 'Penentu Ujian' or . = 'Penentu Ujian')]</value>
      <webElementGuid>4d3978cd-cf45-4635-9af6-386b727d4f63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
