<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Penilaian CBT</name>
   <tag></tag>
   <elementGuidId>62b5100b-4d8a-4e34-9477-c49dbbd4d14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen CBT'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c59f880-fad9-46d3-9e21-a845cacede67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>5aee4f08-b421-4285-b35f-feba548d076b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>13563417-7ee7-4f4b-ae93-7f382d745b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#menu_id=207&amp;action=263</value>
      <webElementGuid>c7b6bfd8-f76b-4836-9a09-025aee640cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>207</value>
      <webElementGuid>e5c853dd-de6c-4186-ae15-ba1a942855a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-xmlid</name>
      <type>Main</type>
      <value>cdn_penilaian_cbt.penilaian_cbt_menu_root</value>
      <webElementGuid>7564862c-48d7-4d0a-abdd-6d9f6eb61714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-id</name>
      <type>Main</type>
      <value>263</value>
      <webElementGuid>ccdf7ae3-232a-40fa-a9b6-54ef39449945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penilaian CBT</value>
      <webElementGuid>b595d37c-e892-4eaa-9240-7cf1b0229bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client mk_sidebar_type_large&quot;]/header[@class=&quot;o_navbar&quot;]/nav[@class=&quot;o_main_navbar&quot;]/div[@class=&quot;mk_apps_sidebar_panel&quot;]/div[@class=&quot;mk_apps_sidebar&quot;]/ul[@class=&quot;mk_apps_sidebar_menu&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>68c5e8ac-3984-44e1-a098-8f6088c0cbcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen CBT'])[1]/following::a[1]</value>
      <webElementGuid>efca7201-1773-40e0-b8f5-d24a9aadaacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskusi'])[2]/following::a[2]</value>
      <webElementGuid>125b52aa-4157-4fb5-bcab-56f487c361e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/preceding::a[1]</value>
      <webElementGuid>96eeec56-515d-4d3b-92bd-5962df085695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#menu_id=207&amp;action=263')]</value>
      <webElementGuid>f21bce0b-b41f-4d36-90f3-d106bea08991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>8ffcf366-6562-46fd-9506-2d9e041d7c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#menu_id=207&amp;action=263' and (text() = 'Penilaian CBT' or . = 'Penilaian CBT')]</value>
      <webElementGuid>588b6444-284a-4aa7-a39b-01f3e7662e01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
